### PR TITLE
Finalize payments

### LINKED ISSUE #32: Handle cancel subscription (distinguish stripe and Paypal)
When user create subscription, write it's id to database 
/payments/$userId/${paymentId}/`{ provider: 'stripe'|'paypal', amount: number }`

### PR DESCRIPTION
**Pull request by stanbar**
closes #32 #33 #52

### CODE REVIEW

**Comment by gbaranski** [comment]
what you want from me to review? @stasbar

**Comment by stasbar** [comment]
Nope, it's just a draft. I will let you know when it's finished.

**Comment by gbaranski** [comment]
i didn't knew about the draft option to make a pull request, i also converted #122 to draft

**Comment by stasbar** [comment]
Yea, it's very useful.

**Comment by stasbar** [comment]
closes #32 #33 #52

**Pull request closed without merging**
