### PR TITLE
Fix Vapetool 2

### PR DESCRIPTION
**Pull request by gbaranski**

### CODE REVIEW

**Comment by gbaranski** [comment]
resolves #115
Screenshot 2020-11-15 at 20 58 35

**Comment by gbaranski** [comment]
Screenshot 2020-11-15 at 22 12 29
Add trash icon next to reset button in mixer

**Comment by gbaranski** [comment]
image
Add loading buttons for calculations
resolved #116

**Comment by gbaranski** [comment]
Screenshot 2020-11-16 at 11 42 03

resolves #118

**Comment by gbaranski** [comment]
Screenshot 2020-11-16 at 14 09 44
Screenshot 2020-11-16 at 14 10 00
I think all of chineese characters that were visible before are now in English

resolved #114

**Comment by gbaranski** [comment]
resolved #117

**Comment by gbaranski** [comment]
Coil calculator tested, everything is working well

**Comment by gbaranski** [comment]
resolved #119

**Comment by gbaranski** [comment]
Screenshot 2020-11-18 at 12 31 54
Fixed style of coil calculator and vg/pg input, rest looks good

resolved #124

**Review by stanbar — APPROVED** [review]
Great job Grzechu. Thank you!

**Pull request merged**
