### PR TITLE
Fix Vapetool

### PR DESCRIPTION
**Pull request by gbaranski**

### CODE REVIEW

**Comment by gbaranski** [comment]
resolves #106

**Comment by gbaranski** [comment]
Screenshot 2020-11-14 at 14 57 24

add Privacy Policy, need also TOS

resolves #45

**Comment by gbaranski** [comment]
Screenshot 2020-11-14 at 15 07 16
Added anonymous login. Resolved showing my account if anonymous

resolves #87

**Review by stasbar — APPROVED** [review]

**Comment by stasbar** [comment]
Now it's fine. Great !

**Pull request merged**
